bazaar/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
import django_cron
import settings

admin.autodiscover()
django_cron.autodiscover()
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'ktj14.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    
    #Admin urls
    url(r'^admin/', include(admin.site.urls)),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    #url(r'^cache.appcache$','index.views.manifest',name='manifest'),
    #Access urls
    url(r'^accounts/', include("users.urls")),
    url(r'^woodstock/', include("woodstock.urls")),
    url(r'^algotrade/', include('algotrade.urls')),
    url(r'^', include("index.urls")),
)
urlpatterns += staticfiles_urlpatterns()

index/urls.py
'''
Created on Jun 12, 2013

@author: Srinivasan
'''
from django.conf.urls import patterns, url


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'ktj14.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', 'index.views.index',name='index'),
    url(r'^forex$', 'index.views.index',name='index'),
    url(r'^commodity/terminal$', 'index.views.commodity_terminal',name='comm_terminal'),
    url(r'^forex/history$', 'index.views.history',name='history'),
    url(r'^commodity/history$', 'index.views.commodity_history',name='comm_history'),
    url(r'^forex/terminal$', 'index.views.terminal',name='terminal'),
    url(r'^forex/closetrade$', 'index.views.closetrade',name='closetrade'),
    url(r'^forex/closetradeall$', 'index.views.closetradeall',name='closetradeall'),
    url(r'^commodity/closetrade$', 'index.views.commclosetrade',name='commclosetrade'),
    url(r'^commodity/closetradeall$', 'index.views.commclosetradeall',name='commclosetradeall'),
    url(r'^commodity/terminal_list$', 'index.views.comm_terminal_list',name='comm_terminal_list'),
    url(r'^forex/trade$', 'index.views.trade',name='trade'),
    url(r'^forex/terminal_list$', 'index.views.terminal_list',name='terminal_list'),
    url(r'^time$', 'index.views.time',name='time'),
    url(r'^indices$', 'index.views.indices',name='indices'),
    url(r'^forex/stocks$', 'index.views.stocks_marquee',name='stocks_marquee'),
    url(r'^forex/basics$', 'index.views.forex_basics',name='forex_basics'),
    url(r'^forex/cancel_order$', 'index.views.cancelbuyorder',name='cancel_buy_order'),
    url(r'^commodity/cancel_order$', 'index.views.cancelbuyordercomm',name='comm_cancel_buy_order'),
    url(r'^forex/transaction', 'index.views.transaction',name='transaction'),
    url(r'^forex/commodity_transaction', 'index.views.commodity_transaction',name='commodity_transaction'),
    url(r'^forex/transact$', 'index.views.transact',name='transact'),
    url(r'^forex/transact_commodity$', 'index.views.transact_commodity',name='transact_commodity'),
    url(r'^forex/help$', 'index.views.help',name='help'),
    url(r'^forex/home$', 'index.views.home',name='home'),
    url(r'^forex/info$', 'index.views.price_info',name='info'),
    url(r'^forex/interface$', 'index.views.interface',name='interface'),
    url(r'^forex/learn$', 'index.views.learn',name='learn'),
    url(r'^forex/pendingorders$', 'index.views.pendingorders',name='pendingorders'),
    url(r'^commodity/pendingorders$', 'index.views.commpendingorders',name='commpendingorders'),
    url(r'^forex/statistics$', 'index.views.statistics',name='statistics'),
    url(r'^forex/toprankers$', 'index.views.toprankers',name='toprankers'),
    url(r'^forex/charts/(?P<type>\w+)/(?P<identifier>\w+)/$', 'index.views.charts',name='charts'),
    url(r'^forex/not_allowed$', 'index.views.not_allowed',name='not_allowed'),
    url(r'^forex/$', 'index.views.index',name='index'),
)

users/urls.py
from django.conf.urls import patterns, url
from users import views
from django.views.decorators.csrf import csrf_exempt


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'ktj14.views.home', name='home'),
    url(r'^nil/', views.nil),
    url(r'^', csrf_exempt(views.login) , name="login"),
    url(r'^login$', csrf_exempt(views.login) , name="account_login"),
    url(r'^logout$', csrf_exempt(views.logout_ktj) , name="account_logout"),
    url(r'^success$', csrf_exempt(views.success) , name="account_success"),
    url(r'^social_login$', csrf_exempt(views.social_login) , name="social_login"),
    url(r'^check_logged$', csrf_exempt(views.check_logged) , name="check_logged"),
    url(r'^profile_exists$', csrf_exempt(views.profile_exists) , name="profile_exists"),
    url(r'^finalists$', views.wsfxFinalists, name='wsfx_finalists'),
   

)

users/models.py
from django.db import models
from django.db.models.fields.related import OneToOneField
from django.conf import settings

USER_TYPES=(("3","Admin"),
            ("1","User"),
            ("2","Member")
            );
            
#Profile Manager for Profile Table Queries (Add functionality if needed)          
class ProfileManager(models.Manager):
    
    use_for_related_fields=True;
    
    def getByYear(self,year):
        return Profile.objects.filter(Year=year);
    
# Profile Model that holds Profile Information
class Profile(models.Model):
    user=OneToOneField(settings.AUTH_USER_MODEL)
    Gender=models.CharField(max_length=1)
    DateOfBirth=models.DateField()
    Institution=models.CharField(max_length=200)
    Country=models.CharField(max_length=100)
    #City=models.CharField(max_length=100,default="szdszd",editable=False)
    State=models.CharField(max_length=100)
    Department=models.CharField(max_length=100)
    Year=models.IntegerField()
    Contact=models.CharField(max_length=20)
    Address=models.TextField()
    #ProfilePic=models.TextField(default="sasd",editable=False)
    RegDate=models.DateTimeField()
    UserType=models.IntegerField(choices=USER_TYPES)
    Social=models.CharField(default="",max_length=10)
    

    #Overriding Manager
    objects=ProfileManager();
    
    def __unicode__(self):
        return self.user.username;
    


class State(models.Model):
    state=models.CharField(max_length=100)
    def user_count(self):
        return Profile.objects.filter(State = self.state).count()
    
    def __unicode__(self):
        return self.state
    
class Department(models.Model):
    department=models.CharField(max_length=100)
    
    def __unicode__(self):
        return self.department

class Institute(models.Model):
    state=models.ForeignKey(State)
    institute=models.CharField(max_length=100)
    def user_count(self):
        return Profile.objects.filter(Institution = self.institute).count()
    def __unicode__(self):
        return self.institute
    
class OldUsers(models.Model):
    email = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    Institution = models.CharField(max_length=100)

users/forms.py
'''
Created on Jun 10, 2013

@author: Srinivasan
'''
from django import forms
from django.contrib.auth.models import User
from django.db import transaction
from django.forms.extras.widgets import SelectDateWidget
from django.contrib.auth import authenticate,login 
from django.utils import timezone
from users.models import Profile,Institute,Department
from django.utils.translation import pgettext
from django.contrib.auth.forms import UserCreationForm
from django.utils.translation import ugettext_lazy as _
from . import app_settings
from urllib2 import urlopen
from json import loads
from models import State
from utils import profile_exists
from app_settings import AuthenticationMethod
from index.models import ForexRankings
from data.models import WudRankings

from django.http.response import HttpResponseRedirect, HttpResponse

BIRTH_YEAR_CHOICES=('1980', '1981', '1982','1983', '1984', '1985','1986', '1987', '1988','1989', '1990', '1991','1992', '1993', '1994','1995', '1996', '1997','1998', '1999', '2000','2001', '2002', '2003','2004', '2005', '2006','2007', '2008', '2009');

GENDER_CHOICES=(('M','Male'),
                ('F','Female'));
                
YEAR_CHOICES=(('1','1st'),('2','2nd'),('3','3rd'),('4','4th'),('5','5th'),('6','Postgraduate Ist'),('7','Postgraduate IInd'),('8','Postgraduate IIIrd'),('9','Other'));

STATES={'':'Choose State'}
INSTITUTES={'':'Choose State'}
DEPARTMENT={}

class PasswordField(forms.CharField):

    def __init__(self, *args, **kwargs):
        render_value = kwargs.pop('render_value', 
                                  app_settings.PASSWORD_INPUT_RENDER_VALUE)
        kwargs['widget'] = forms.PasswordInput(render_value=render_value, 
                                               attrs={'placeholder': _('Password')})
        super(PasswordField, self).__init__(*args, **kwargs)

class SetPasswordField(PasswordField):

    def clean(self, value):
        value = super(SetPasswordField, self).clean(value)
        min_length = app_settings.PASSWORD_MIN_LENGTH
        if len(value) < min_length:
            raise forms.ValidationError(_("Password must be a minimum of {0} "
                                          "characters.").format(min_length))
        return value


class ProfileForm(forms.Form):
    username=forms.CharField(max_length=30,label='Username')
    email=forms.EmailField(max_length=75,label='Email')
    password1 = SetPasswordField(label=_("Password"),required=False)
    password2 = PasswordField(label=_("Password (again)"),required=False)
    firstname=forms.CharField(max_length=30,label='Firstname')
    lastname=forms.CharField(max_length=30,label='Lastname')
    gender=forms.ChoiceField(choices=GENDER_CHOICES,label='Gender')
    dateofbirth=forms.DateField(label='Date Of Birth',widget = SelectDateWidget(years=BIRTH_YEAR_CHOICES,))
    institution=forms.ChoiceField(choices=INSTITUTES,label='Institution')
    country=forms.CharField(max_length=100,label='Country')
    state=forms.ChoiceField(choices=STATES,label='State')
    department=forms.ChoiceField(choices=DEPARTMENT,label='Department')
    year=forms.ChoiceField(choices=YEAR_CHOICES,label='Year')
    contact=forms.CharField(max_length=20,label='Contact')
    address=forms.CharField(widget=forms.Textarea)
    social=forms.CharField(required=False)
    #profilepic=forms.CharField()
    
    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)
        st=State.objects.all()
        for stat in st:
            STATES[stat.state]=stat.state
        self.fields['state'].choices=STATES.items()
        insti=Institute.objects.all()
        for inst in insti:
           INSTITUTES[inst.institute]=inst.institute
            
        dept=Department.objects.all()
        for dep in dept:
            DEPARTMENT[dep.department]=dep.department
        self.fields['institution'].choices=INSTITUTES.items()
        self.fields['department'].choices=DEPARTMENT.items()
        self.fields['email'].required = True
        self.fields['email'].label = 'Email Address'
        
    def clean(self):
        if self._errors:
            return
        ur=User.objects.filter(username=self.cleaned_data['username'])
        if ur.count()>=1:
            raise forms.ValidationError(_("Username Exists"))
        ur=User.objects.filter(email=self.cleaned_data['email'])
        if ur.count()>=1:
            raise forms.ValidationError(_("User with Email Exists"))
        if self.cleaned_data['password1']!=self.cleaned_data['password2']:
            raise forms.ValidationError(_("Confirm password not Matching"))
        return self.cleaned_data
        
    def create_user(self, commit=True):
        if app_settings.USERNAME_REQUIRED:
            username = self.cleaned_data["username"]
        else:
            username = None
        data = self.initial
        user = User(username=username,email=self.cleaned_data["email"].strip().lower())
        user.set_unusable_password()
        if commit:
            user.save()
        password = self.cleaned_data.get("password1")
        if password:
            user.set_password(password)
        if commit:
            user.save()
        return user
    
    
    @transaction.commit_on_success
    def save(self):
        try:
            if self.is_valid():
                user = User()
                user.username=self.cleaned_data['username']
                user.email=self.cleaned_data['email']
                user.set_password(self.cleaned_data['password1'])
                user.first_name=self.cleaned_data['firstname']
                user.last_name=self.cleaned_data['lastname']
                user.save();
                new_user=User.objects.get(pk=user.id)
                profile=Profile();
                profile.user=new_user;
                profile.Gender=self.cleaned_data['gender']
                profile.DateOfBirth=self.cleaned_data['dateofbirth']
                profile.Institution=self.cleaned_data['institution']
                profile.Country=self.cleaned_data['country']
                #profile.City=self.cleaned_data['city']
                profile.State=self.cleaned_data['state']
                profile.Department=self.cleaned_data['department']
                profile.Year=self.cleaned_data['year']
                profile.Contact=self.cleaned_data['contact']
                profile.Address=self.cleaned_data['address']
                #profile.ProfilePic=self.cleaned_data['profilepic']
                profile.RegDate=timezone.now()
                profile.UserType=1
                profile.save()
        except:
            if user is not None:
                user.delete()
            

class SocialForm(forms.Form):
    username=forms.CharField(max_length=30,label='Username')
    email=forms.EmailField(max_length=75,label='Email')
    firstname=forms.CharField(max_length=30,label='Firstname')
    lastname=forms.CharField(max_length=30,label='Lastname')
    gender=forms.ChoiceField(choices=GENDER_CHOICES,label='Gender')
    dateofbirth=forms.DateField(label='Date Of Birth',widget = SelectDateWidget(years=BIRTH_YEAR_CHOICES,))
    institution=forms.ChoiceField(choices=INSTITUTES,label='Institution')
    country=forms.CharField(max_length=100,label='Country')
    state=forms.ChoiceField(choices=STATES,label='State')
    department=forms.ChoiceField(choices=DEPARTMENT,label='Department')
    year=forms.ChoiceField(choices=YEAR_CHOICES,label='Year')
    contact=forms.CharField(label='Contact')
    address=forms.CharField(widget=forms.Textarea)
    social=forms.CharField(required=False)
    #profilepic=forms.CharField()
    
    def __init__(self, *args, **kwargs):
        super(SocialForm, self).__init__(*args, **kwargs)
        st=State.objects.all()
        for stat in st:
            STATES[stat.state]=stat.state
        self.fields['state'].choices=STATES.items()
        insti=Institute.objects.all()
        for inst in insti:
            INSTITUTES[inst.institute]=inst.institute
            
        dept=Department.objects.all()
        for dep in dept:
            DEPARTMENT[dep.department]=dep.department
        self.fields['institution'].choices=INSTITUTES.items()
        self.fields['department'].choices=DEPARTMENT.items()
        self.fields['email'].required = True
        self.fields['email'].label = 'Email Address'
        
    def clean(self):
        if self._errors:
            return
        ur=User.objects.filter(username=self.cleaned_data['username'])
        if ur.count()>=1:
            raise forms.ValidationError(_("Username Exists"))
        ur=User.objects.filter(email=self.cleaned_data['email'])
        if ur.count()>=1:
            raise forms.ValidationError(_("User with Email Exists"))
        return self.cleaned_data
        
    def create_user(self, commit=True):
        if app_settings.USERNAME_REQUIRED:
            username = self.cleaned_data["username"]
        else:
            username = None
        data = self.initial
        user = User(username=username,email=self.cleaned_data["email"].strip().lower())
        user.set_unusable_password()
        if commit:
            user.save()
        password = timezone.now()
        if password:
            user.set_password(password)
        if commit:
            user.save()
        return user
    
    
    @transaction.commit_on_success
    def save(self):
        try:
            if self.is_valid():
                user = User()
                user.username=self.cleaned_data['social']+'_'+self.cleaned_data['username']
                user.email=self.cleaned_data['email']
                user.set_password(timezone.now())
                user.first_name=self.cleaned_data['firstname']

users/templates/facebook_signup.html
{% load url from future %}
{% load i18n %}
{% load static%}
   

{% block content %}


<form class="signup" id="signup_form" method="post" action="{% url 'facebook_signup' %}">
	
  
  {% csrf_token%}
  <div class="register-section">
        <div class="register-wrap">
            <div class="label">{{ form.username.label }}</div> 
            <div class="input-element" id="username-input">{{form.username.value}}</div>
        </div>
        <div class="register-wrap">
            <div class="label">{{ form.email.label }}</div> 
            <div class="input-element" id="email-input">{{form.email.value}}</div>
        </div>
        <div class="register-wrap">
            <div class="label">Password</div> 
            <div class="input-element" id="password1-input">Not Required</div>
        </div>
        <div class="register-wrap">
            <div class="label">Confirm Password</div> 
            <div class="input-element" id="password2-input">Not Required</div>
        </div>
  </div>
  <div class="register-section">
        <div class="register-wrap">
            <div class="label">Name</div> 
            <div class="input-element">{{ form.firstname }}{{ form.lastname }}</div>
        </div>
        <div class="register-wrap">
            <div class="label">{{form.gender.label}}</div> 
            <div class="input-element">{{ form.gender }}</div>
        </div>
        <div class="register-wrap">
            <div class="label">{{form.dateofbirth.label}}</div> 
            <div class="input-element">{{ form.dateofbirth }}</div>
        </div>
        <div class="register-wrap">
            <div class="label">{{form.contact.label}}</div> 
            <div class="input-element">{{ form.contact }}</div>
        </div>
  </div>
  <div class="register-section">
        <div class="register-wrap">
            <div class="label">{{form.country.label}}</div> 
            <div class="input-element">{{ form.country }}</div>
        </div>
        <div class="register-wrap">
            <div class="label">{{form.state.label}}</div> 
            <div class="input-element">{{ form.state }}</div>
        </div>
        <div class="register-wrap">
            <div class="label">{{form.department.label}}</div> 
            <div class="input-element">{{ form.department }}</div>
        </div>
        <div class="register-wrap">
            <div class="label"><label for="id_firstname">{{form.year.label}}</label></div> 
            <div class="input-element">{{ form.year }}</div>
        </div>
  </div>
  
   <div class="register-section">
        <div class="register-wrap">
            <div class="label">{{form.institution.label}}</div> 
            <div class="input-element">{{ form.institution }}</div>
        </div>
        <div class="register-wrap">
            <div class="label">{{form.address.label}}</div> 
            <div class="input-element">{{ form.address }}</div>
        </div>
        <div class="register-wrap">
        {% if form.errors %}
  		<div class="error">All Fields Mandatory. Password Minimum 6 Characters</div>
  		{% endif %}
  		</div>
  		<div class="register-wrap">
  		<div class="input-element"><button type="button" onclick="FBsignup()">Signup</button></div>
  		</div>
  </div>
  
     <div class="register-section">
  <div class="register-wrap" id="social-reg">
{{form.non_field_errors}}
</div>
</div>
  
  <a onclick="cancelAuthorization()"><img src="https://lh3.googleusercontent.com/-t1VxWEIwgkI/UiyEKavxhgI/AAAAAAAABwI/kIq3Ef3yec4/s24-no/exit.png"></a>
</form>




{% endblock %}



users/templates/finalists.html
<div style='text-align:center;'>
{% for user in users %}
{{user}}<br>
{% endfor %}
</div>

users/templates/google_signup.html
{% load url from future %}
{% load i18n %}
{% load static%}
   

{% block content %}


<form class="signup" id="signup_form" method="post" action="{% url 'google_signup' %}">
	
  {% csrf_token%}
  <div class="register-section">
        <div class="register-wrap">
            <div class="label">{{ form.username.label }}</div> 
            <div class="input-element" id="username-input">{{form.username.value}}</div>
        </div>
        <div class="register-wrap">
            <div class="label">{{ form.email.label }}</div> 
            <div class="input-element" id="email-input">{{form.email.value}}</div>
        </div>
        <div class="register-wrap">
            <div class="label">Password</div> 
            <div class="input-element" id="password1-input">{{ form.password1.value }}</div>
        </div>
        <div class="register-wrap">
            <div class="label">Confirm Password</div> 
            <div class="input-element" id="password2-input">{{ form.password2.value }}</div>
        </div>
  </div>
  <div class="register-section">
        <div class="register-wrap">
            <div class="label">Name</div> 
            <div class="input-element">{{ form.firstname }}{{ form.lastname }}</div>
        </div>
        <div class="register-wrap">
            <div class="label">{{form.gender.label}}</div> 
            <div class="input-element">{{ form.gender }}</div>
        </div>
        <div class="register-wrap">
            <div class="label">{{form.dateofbirth.label}}</div> 
            <div class="input-element">{{ form.dateofbirth }}</div>
        </div>
        <div class="register-wrap">
            <div class="label">{{form.contact.label}}</div> 
            <div class="input-element">{{ form.contact }}</div>
        </div>
  </div>
  <div class="register-section">
        <div class="register-wrap">
            <div class="label">{{form.country.label}}</div> 
            <div class="input-element">{{ form.country }}</div>
        </div>
        <div class="register-wrap">
            <div class="label">{{form.state.label}}</div> 
            <div class="input-element">{{ form.state }}</div>
        </div>
        <div class="register-wrap">
            <div class="label">{{form.department.label}}</div> 
            <div class="input-element">{{ form.department }}</div>
        </div>
        <div class="register-wrap">
            <div class="label"><label for="id_firstname">{{form.year.label}}</label></div> 
            <div class="input-element">{{ form.year }}</div>
        </div>
  </div>
  
   <div class="register-section">
        <div class="register-wrap">
            <div class="label">{{form.institution.label}}</div> 
            <div class="input-element">{{ form.institution }}</div>
        </div>
        <div class="register-wrap">
            <div class="label">{{form.address.label}}</div> 
            <div class="input-element">{{ form.address }}</div>
        </div>
        <div class="register-wrap">
        {% if form.errors %}
  		<div class="error">All Fields Mandatory. Password Minimum 6 Characters</div>
  		{% endif %}
  		</div>
  		<div class="register-wrap">
  		<div class="input-element"><button type="button" onclick="GPsignup()">Signup</button></div>
  		</div>
  </div>
  
    <div class="register-section">
  <div class="register-wrap" id="social-reg">
{{form.non_field_errors}}
</div>
</div>
  
  <a onclick="cancelGoogleAuthorization()"><img src="{% static 'img/exit.png' %}"></a>
</form>




{% endblock %}



users/templates/profile.html
{% load url from future %}
{% load i18n %}
{% load static%}
   

{% block content %}

  <div class="register-section">
        <div class="register-wrap">
            <div class="label">Username</div> 
            <div class="input-element">{{user.username}}</div>
        </div>
        <div class="register-wrap">
            <div class="label">Email</div> 
            <div class="input-element">{{user.email}}</div>
        </div>
        <div class="register-wrap">
            <div class="label">Password</div> 
            <div class="input-element">*****</div>
        </div>
  </div>
  <div class="register-section">
        <div class="register-wrap">
            <div class="label">Name</div> 
            <div class="input-element">{{ user.first_name }}{{ user.last_name }}</div>
        </div>
        <div class="register-wrap">
            <div class="label">Gender</div> 
            <div class="input-element">{{ profile.Gender }}</div>
        </div>
        <div class="register-wrap">
            <div class="label">Date Of Birth</div> 
            <div class="input-element">{{ profile.DateOfBirth }}</div>
        </div>
        <div class="register-wrap">
            <div class="label">Contact</div> 
            <div class="input-element">{{ profile.Contact }}</div>
        </div>
  </div>
  <div class="register-section">
        <div class="register-wrap">
            <div class="label">Country</div> 
            <div class="input-element">{{ profile.Country }}</div>
        </div>
        <div class="register-wrap">
            <div class="label">State</div> 
            <div class="input-element">{{ profile.State }}</div>
        </div>
        <div class="register-wrap">
            <div class="label">Department</div> 
            <div class="input-element">{{ profile.Department }}</div>
        </div>
        <div class="register-wrap">
            <div class="label"><label for="id_firstname">Year</label></div> 
            <div class="input-element">{{ profile.Year }}</div>
        </div>
  </div>
  
   <div class="register-section">
        <div class="register-wrap">
            <div class="label">Institution</div> 
            <div class="input-element">{{ profile.Institution }}</div>
        </div>
        <div class="register-wrap">
            <div class="label">Address</div> 
            <div class="input-element">{{ profile.Address }}</div>
        </div>
        <div class="register-wrap">
  		</div>
  </div>
  




{% endblock %}



users/templates/signup.html
{% load url from future %}
{% load i18n %}
{% load static%}
   

{% block content %}


<form class="signup" id="signup_form" method="post" action="{% url 'account_signup' %}">
  
  {% csrf_token%}
  <div class="register-section">
        <div class="register-wrap">
            <div class="label">{{ form.username.label }}</div> 
            <div class="input-element" id="username-input">{{ form.username }}</div>
        </div>
        <div class="register-wrap">
            <div class="label">{{ form.email.label }}</div> 
            <div class="input-element" id="email-input">{{ form.email }}</div>
        </div>
        <div class="register-wrap">
            <div class="label">{{ form.password1.label }}</div> 
            <div class="input-element">{{ form.password1 }}</div>
        </div>
        <div class="register-wrap">
            <div class="label">{{ form.password2.label }}</div> 
            <div class="input-element">{{ form.password2 }}</div>
        </div>
  </div>
  <div class="register-section">
        <div class="register-wrap">
            <div class="label">Name</div> 
            <div class="input-element">{{ form.firstname }}{{ form.lastname }}</div>
        </div>
        <div class="register-wrap">
            <div class="label">{{form.gender.label}}</div> 
            <div class="input-element">{{ form.gender }}</div>
        </div>
        <div class="register-wrap">
            <div class="label">{{form.dateofbirth.label}}</div> 
            <div class="input-element">{{ form.dateofbirth }}</div>
        </div>
        <div class="register-wrap">
            <div class="label">{{form.contact.label}}</div> 
            <div class="input-element">{{ form.contact }}</div>
        </div>
  </div>
  <div class="register-section">
        <div class="register-wrap">
            <div class="label">{{form.country.label}}</div> 
            <div class="input-element">{{ form.country }}</div>
        </div>
        <div class="register-wrap">
            <div class="label">{{form.state.label}}</div> 
            <div class="input-element">{{ form.state }}</div>
        </div>
        <div class="register-wrap">
            <div class="label">{{form.department.label}}</div> 
            <div class="input-element">{{ form.department }}</div>
        </div>
        <div class="register-wrap">
            <div class="label"><label for="id_firstname">{{form.year.label}}</label></div> 
            <div class="input-element">{{ form.year }}</div>
        </div>
  </div>
  
   <div class="register-section">
        <div class="register-wrap">
            <div class="label">{{form.institution.label}}</div> 
            <div class="input-element">{{ form.institution }}</div>
        </div>
        <div class="register-wrap">
            <div class="label">{{form.address.label}}</div> 
            <div class="input-element">{{ form.address }}</div>
        </div>
        <div class="register-wrap">
        {% if form.errors %}
  		<div class="error">All Fields Mandatory. Password Minimum 6 Characters.</div>
  		{% endif %}
  		</div>
  		<div class="register-wrap">
  		<div class="input-element"><button type="button" onclick="signup()">Signup</button></div>
  		</div>
  </div>
  
  <div class="register-section">
  	<div class="register-wrap" id="social-reg">
  	<a class="social-reg" onclick="facebook_login()"><img src="https://lh5.googleusercontent.com/-axMPGZWxufo/UiyD3vOTatI/AAAAAAAABv0/PKbcvYzj10Q/w179-h30-no/fb.png"></a>

  	</div>
  	<div class="register-wrap" id="social-reg">
  	<span id="signinButton">
  <div id="gplus_register" class="customGPlusSignIn social-reg">
  	<img src="{% static 'img/users/g+.png'%}">
  </div>
</span>
</div>

<div class="register-wrap" id="social-reg">
{{form.non_field_errors}}
</div>

  </div>
  
    <a onclick="register()"><img src="https://lh3.googleusercontent.com/-t1VxWEIwgkI/UiyEKavxhgI/AAAAAAAABwI/kIq3Ef3yec4/s24-no/exit.png"></a>
  
</form>


{% endblock %}

